baseurl = "https://brege.org/"
title = "brege.org"
copyright = "Copyright 2016-2017 Wyatt Brege"

PygmentsCodeFences = true
pygmentsStyle = "emacs"

theme = "hugo-academic"
enableEmoji = true
favicon = "img/icon.png"

footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  color_theme = "default"
  font = "default"

  name = "Wyatt Brege"
  role = "Computational Astrophysicist - Chef"
  organization = ""
  avatar = "portrait.png"
  email = "wyatt@brege.org"
#  pubkey = "C504 FC55 11E3 69C5 9B78  71F9 EB3F 25A8 C557 9EA6"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "brege"

  logo = ""

  map = 0
  map_api_key = ""
  latitude = ""
  longitude = ""
  zoom = 15

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  time_format = "15:04"

  reading_time = true

  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true
 
  # Enable global source code highlighting
#  highlight = false
#  highlight = true
#  highlight_languages = []
#  highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

#######################################
#  # Publication types.
#  #   Used to categorize publications.
#  #   The index of the publication type in the list is used as its unique numerical identifier.
#  #   The numeric ID is used in a publication's frontmatter to categorize it.
#  #   The language can be edited below.
#  #   For multi-lingual sites, copy this block to each language section at the end of this file.
#  publication_types = [
#    'Uncategorized',  # 0
#    'Conference proceedings',  # 1
#    'Journal',  # 2
#    'Work in progress',  # 3
#    'Technical report',  # 4
#    'Book',  # 5
#    'Book chapter'  # 6
#  ]
#
#  # Configuration of talk pages.
#  [params.talks]
#    # Show talk time?
#    time = true
#
#  # Configuration of publication pages.
#  [params.publications]
#    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
#    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#    date_format = "January, 2006"
#
#  # Configuration of project pages.
#  [params.projects]
#    # List publications and talks related to the project?
#    list_children = true
#
#    # Publication list format.
#    #   0 = Simple
#    #   1 = Detailed
#    #   2 = APA
#    #   3 = MLA
#    publication_format = 3
#
#######################################

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:wyatt@brege.org"

  [[params.social]]
    icon = "rss"
    icon_pack = "fa"
    link = "/post/index.xml"

  [[params.social]]
    icon = "google-plus"
    icon_pack = "fa"
    link = "//plus.google.com/u/0/+WyattBrege"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/brege"

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "//arxiv.org/find/astro-ph/1/au:+Brege_W"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "//scholar.google.com/citations?user=WsjvDuQAAAAJ"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

[[menu.main]]
  name = "CV"
  url = "/brege-cv.pdf"
  weight = 5

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"

