baseurl = "https://brege.org/"
title = "brege.org"
copyright = "&copy; 2016 Wyatt Brege"
languageCode = "en-us"
theme = "hugo-academic"
favicon = "img/favicon.ico"

# Enable comments by entering your Disqus shortname
#disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
#googleAnalytics = ""


[params]
  name = "Wyatt Brege"
  role = "Doctoral Student in Computational Astrophysics"
  organization = "Washington State University"
  avatar = "portrait.png"
  email = "wyatt@brege.org"
#  address = "Stanford AI Lab, Stanford University, California, 90210, USA."
#  phone = "888 888 88 88"


  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:wyatt@brege.org"

  [[params.social]]
    icon = "google-plus"
    icon_pack = "fa"
    link = "https://plus.google.com/u/0/+WyattBrege"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/brege"

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4
