baseurl = "https://brege.org/"
title = "brege.org"
copyright = "Copyright 2016 Wyatt Brege"
languageCode = "en-us"
PygmentsCodeFences = true
pygmentsStyle = "emacs"

theme = "hugo-academic"
#favicon = "img/favicon.ico"
favicon = "img/icon.png"

footnotereturnlinkcontents = "<sup>^</sup>"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  name = "Wyatt Brege"
  role = "Researcher in Computational Astrophysics"
  organization = "Washington State University"
  avatar = "portrait.png"
  email = "wyatt@brege.org"
#  pubkey = "C504 FC55 11E3 69C5 9B78  71F9 EB3F 25A8 C557 9EA6"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "brege"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false
 
  # Enable global source code highlighting
  highlight = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:wyatt@brege.org"

  [[params.social]]
    icon = "rss"
    icon_pack = "fa"
    link = "/post/index.xml"

  [[params.social]]
    icon = "google-plus"
    icon_pack = "fa"
    link = "//plus.google.com/u/0/+WyattBrege"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/brege"

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "//arxiv.org/find/astro-ph/1/au:+Brege_W"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "//scholar.google.com/citations?user=WsjvDuQAAAAJ"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

#[[menu.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

[[menu.main]]
  name = "CV"
  url = "/brege-cv.pdf"
  weight = 5
