#!/bin/bash
HOST=brege.org
DIR=/usr/share/nginx/brege.org/

# Check for a valid Hugo installation
if ! which hugo > /dev/null; then
  echo "Error: Hugo not found"
  exit 1
fi

# Check if the public directory exists
if [ -d "public" ]; then
  rm -rf public
fi

# Build hugo site:
hugo --buildDrafts=false 

# Check if the build was successful
if [ $? -ne 0 ]; then
  echo "Error: Hugo build failed"
  exit 1
fi

# Try to clean the whitespace left by hugo's
if command -v tidy > /dev/null; then
  find public/ -name "*.html" -exec tidy -i 2 -m {} \; > /dev/null
else
  echo "Warning: Tidy is not installed on this system."
fi

# Deploy to $HOST
rsync -avz --delete --exclude=".well-known" public/ ${HOST}:${DIR}

exit 0
