baseURL = "https://brege.org"
copyright = "Copyright (c) 2016-2026 Wyatt Brege"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = false
enableInlineShortcodes = true

enableEmoji = true
ignoreFiles = ['(?:^|/)README\.md$']

theme = "gastrophysics"
title = "brege.org"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[params]
  author = "Wyatt Brege"
  # linen, rose-pine, rose-pine-moon, catppuccin-frappe,
  # catppuccin-macchiato, catppuccin-mocha, nord,
  # gruvbox, everforest, sepia
  #color = 'linen'
  colorLight = 'linen'
  colorDark = 'nord'
  env = 'production'
  twitter = ''
  github = 'brege'
  instagram = ''
  mastodon = 'brege@mastodon.social'
  matrix = '@brege:matrix.org'
  signal = '@brege.01'
  avatar = 'wyatt@brege.org'
  name = 'Wyatt Brege'
  bio = 'gastrophysicist'

  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowReadingTime = false
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowFullTextinRSS = true
  ShowRssButtonInSectionTermList = true
  hideFooter = true

  showRelatedPosts = true
  TocOpen = true
  ShowToc = true

  defaultTheme = 'auto' 
  disableScrollToTop = true
  disableAnchorHeadings = false

  mainSections = ['post']
  homePageSize = 6
  postPageSize = 20

[params.heroCards]
  defaultView = 'expanded'

  [params.heroCards.compact]
    summary = true

  [params.heroCards.expanded]
    summary = true

[params.postCards]
  defaultView = 'compact'

  [params.postCards.compact]
    summary = true

  [params.postCards.expanded]
    summary = true

[params.editPost]
  URL = "https://github.com/brege/brege.org/tree/master/content"
  Text = "edit"
  appendFilePath = true

[params.homeInfoParams]
  Title = 'Wyatt Brege'
  FeedTitle = 'Articles'
  Content = """
  I simulated
  [black-hole neutron-star mergers](https://black-holes.org)
  for my 
  [physics PhD](https://hdl.handle.net/2376/111818)
  at
  [WSU](https://physics.wsu.edu/).
  I'm also a 
  [professional chef](/recipes)
  with a love for seafood, sauces, soups and organic produce.
  A lifelong believer in 
  [free software](https://www.gnu.org/philosophy/free-sw.en.html),
  I build apps and tools across
  [AI](https://github.com/brege#agents),
  [data science](/categories/data-science/),
  and [Linux](https://github.com/brege#apps).

  """
[[params.homeInfoParams.markers]]
  name = 'my bio'
  url = '/about'
[[params.homeInfoParams.markers]]
  name = 'my CV'
  url = '/cv'
[[params.homeInfoParams.markers]]
  name = 'google scholar'
  url = 'https://scholar.google.com/citations?user=WsjvDuQAAAAJ'
[[params.homeInfoParams.markers]]
  name = "farmer's market menus"
  url = '/recipes/menus'

[params.profileMode]
  enabled = false
  title = "Wyatt Brege"
  subtitle = 'Gastrophysicist'
  imageUrl = "/img/portrait.png"
  imageTitle = ''
  imageWidth = 120
  imageHeight = 120
[[params.profileMode.buttons]]
  name = 'Recent'
  url = '/post'
[[params.profileMode.buttons]]
  name = 'Bio'
  url = '/about'
[[params.profileMode.buttons]]
  name = 'Resume'
  url = '/cv'

[[params.socialIcons]]
  name = 'email'
  url = 'mailto:wyatt@brege.org'
[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/brege'
[[params.socialIcons]]
  name = 'mastodon'
  url = 'https://mastodon.social/@brege'
[[params.socialIcons]]
  name = 'signal'
  url = 'https://signal.me/#eu/0qONLHRq0LrobBU7QIEfqomo1LJ9425RBq5IzydUPCa3hLGuq61AzLhY4Xjvt0e8'
[[params.socialIcons]]
  name = 'matrix'
  url = 'https://matrix.to/#/@brege:matrix.org'
[[params.socialIcons]]
  name = 'linkedin'
  url = 'https://linkedin.com/in/wyatt-brege/'

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    ordered = true
    startLevel = 1
    endLevel = 4

[menu]

  [[menu.main]]
    identifier = "search"
    name = "search"
    url = "/search"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "post"
    name = "posts"
    url = "/post"
    weight = 20
  [[menu.main]]
    identifier = "recipes"
    name = "recipes"
    url = "/recipes"
    weight = 25
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 30
  [[menu.main]]
    identifier = "cv"
    name = "resumé"
    url = "/cv"
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

[pagination]
  pagerSize = 20

[caches]
  [caches.getresource]
    maxAge = "10m"
